#include "format.h"

// Define color pairs 
unordered_map<short, string> effect_mapping = {
    {c_grass      ,   italic},
    {c_dragon     ,   bold},
    {c_key        ,   blink},
    {c_lightoff   ,   dim}
}; 

// Define effect pairs
unordered_map<short, string> color_mapping = {
    {c_dtopleft       ,  font_white},
    {c_dtopright  ,   font_white},
    {c_dbottomleft  ,  font_white},
    {c_dbottomright ,  font_white},
    {c_dhorizontal  ,  font_white},
    {c_dverticalleft ,  font_white},
    {c_dverticalright ,  font_white},
    {c_dverticalmiddle ,  font_white},
    {c_dtopcross ,  font_white},
    {c_dbottomcross ,  font_white},
    {c_dleftcross ,  font_white},
    {c_drightcross ,  font_white},
    {c_dmiddlecross ,  font_white},
    {c_stopleft ,  font_white},
    {c_srightleft ,  font_white},
    {c_sbottomleft ,  font_white},
    {c_sbottomright ,  font_white},
    {c_shorizontal ,  font_white},
    {c_sverticalleft ,  font_white},
    {c_sverticalright ,  font_white},
    {c_sverticalmiddle ,  font_white},
    {c_stopcross ,  font_white},
    {c_sbottomcross ,  font_white},
    {c_sleftcross ,  font_white},
    {c_srightcross ,  font_white},
    {c_smiddlecross ,  font_white},
    {c_bed ,  font_green},
    {c_bedleft ,  font_green},
    {c_bedright ,  font_green},
    {c_bedcentre ,  font_green},
    {c_bedmiddle ,  font_green},
    {c_leftchair ,  font_cyan},
    {c_rightchair ,  font_cyan},
    {c_door ,  font_yellow},
    {c_leftdoor ,  font_yellow},
    {c_rightdoor ,  font_yellow},
    {c_lightoff ,  font_purple},
    {c_lighton ,  font_purple},
    {c_treasure ,  font_yellow},
    {c_key ,  font_yellow},
    {c_leftcupboard ,  font_white},
    {c_rightcupboard ,  font_white},
    {c_npc ,  font_yellow},
    {c_tree ,  font_purple},
    {c_treebranch ,  font_purple},
    {c_treeleft ,  font_purple},
    {c_treeright ,  font_purple},
    {c_grass ,  font_green},
    {c_leaveleft ,  font_green},
    {c_leaveright ,  font_green},
    {c_dmbottomleft ,  font_white},
    {c_dmbottomright ,  font_white},
    {c_bush ,  font_green},
    {c_brick ,  font_red},
    {c_castle ,  font_white},
    {c_flag ,  font_yellow},
    {c_hole ,  font_cyan},
    {c_stairs1 ,  font_yellow},
    {c_stairs2 ,  font_yellow},
    {c_stairs3 ,  font_yellow},
    {c_stairs4 ,  font_yellow},
    {c_stairs5 ,  font_yellow},
    {c_stairs6 ,  font_yellow},
    {c_stairs7 ,  font_yellow},
    {c_dragonnpc ,  font_purple},
    {c_dragon ,  font_red},
    {c_deaddragonnpc ,  font_purple},
    {c_deaddragon ,  font_red},
    {c_player ,  font_blue},
    {c_oldman ,  font_green},
    {c_rooftop1 ,  font_purple},
    {c_rooftop2 ,  font_purple},
    {c_rooftop3 ,  font_purple},
    {c_rooftop4 ,  font_purple},
    {c_knob ,  font_yellow},
    {c_rooftop5 ,  font_purple},
    {c_rooftop6 ,  font_purple}
};
