#include "format.h"

// Define color pairs 
unordered_map<short, string> effect_mapping = {
    {c_grass      ,   italic},
    {c_dragon     ,   bold},
    {c_key        ,   blink},
    {c_lightoff   ,   dim},
    {c_gamemaster,  bold}
}; 

// Define effect pairs
unordered_map<short, string> color_mapping = {
    {c_wall ,  font_white},
    {c_hero , font_blue},
    {c_girl , font_purple},
    {c_bed ,  font_green},
    {c_bedleft ,  font_green},
    {c_bedright ,  font_green},
    {c_bedcentre ,  font_green},
    {c_bedmiddle ,  font_green},
    {c_leaveleft ,  font_green},
    {c_leaveright ,  font_green},
    {c_table ,  font_cyan},
    {c_chair ,  font_blue},
    {c_door ,  font_yellow},
    {c_leftdoor ,  font_yellow},
    {c_rightdoor ,  font_yellow},
    {c_lightoff ,  font_yellow},
    {c_lighton ,  font_yellow},
    {c_treasure ,  font_yellow},
    {c_key ,  font_yellow},
    {c_leftcupboard ,  font_cyan},
    {c_rightcupboard ,  font_cyan},
    {c_npc ,  font_yellow},
    {c_tree ,  font_green},
    {c_treebranch ,  font_purple},
    {c_treeleft ,  font_green},
    {c_treeright ,  font_green},
    {c_grass ,  font_green},
    {c_bush ,  font_purple},
    {c_brick ,  font_yellow},
    {c_castle ,  font_white},
    {c_flag ,  font_red},
    {c_hole ,  font_cyan},
    {c_stairs1 ,  font_white},
    {c_stairs2 ,  font_white},
    {c_stairs3 ,  font_white},
    {c_stairs4 ,  font_white},
    {c_stairs5 ,  font_white},
    {c_stairs6 ,  font_white},
    {c_stairs7 ,  font_white},
    {c_dragonnpc ,  font_purple},
    {c_dragon ,  font_red},
    {c_deaddragonnpc ,  font_red},
    {c_deaddragon ,  font_purple},
    {c_oldman ,  font_cyan},
    {c_rooftop1 ,  font_white},
    {c_rooftop2 ,  font_white},
    {c_rooftop3 ,  font_white},
    {c_rooftop4 ,  font_white},
    {c_rooftop5 ,  font_white},
    {c_rooftop6 ,  font_white},
    {c_knob ,  font_yellow},
    {c_leftwardrobe ,  font_cyan},
    {c_rightwardrobe ,  font_cyan},
    {c_librarian ,  font_yellow},
    {c_penny ,  font_yellow},
    {c_haley ,  font_yellow},
    {c_cooper ,  font_yellow},
    {c_robert ,  font_yellow},
    {c_castlewall ,  font_white},
    {c_stairs8 ,  font_white},
    {c_stairs9 ,  font_white},
    {c_chair1 ,  font_cyan},
    {c_chair2 ,  font_cyan},
    {c_chair3 ,  font_cyan},
    {c_chair4 ,  font_cyan},
    {c_chair5 ,  font_cyan},
    {c_chair6 ,  font_cyan},
    {c_chair7 ,  font_cyan},
    {c_chair8 ,  font_cyan},
    {c_chair9 ,  font_cyan},
    {c_chair10 ,  font_cyan},
    {c_chair11 ,  font_cyan},
    {c_chair12 ,  font_cyan},
    {c_chair13 ,  font_cyan},
    {c_chair14 ,  font_cyan},
    {c_chair15 ,  font_cyan},
    {c_chair16 ,  font_cyan},
    {c_chair17 ,  font_cyan},
    {c_chair18 ,  font_cyan},
    {c_chair19 ,  font_cyan},
    {c_lamp1 ,  font_yellow},
    {c_lamp2 ,  font_yellow},
    {c_lamp3 ,  font_yellow},
    {c_lamp4 ,  font_yellow},
    {c_lamp5 ,  font_yellow},
    {c_lamp6 ,  font_yellow},
    {c_lamp7 ,  font_yellow},
    {c_lamp8 ,  font_yellow},
    {c_chair20 ,  font_cyan},
    {c_chair21 ,  font_cyan},
    {c_chair22 ,  font_cyan},
    {c_chair23 ,  font_cyan},
    {c_lamp9 ,  font_yellow},
    {c_lamp10 ,  font_yellow},
    {c_monster , font_cyan},
    {c_gamemaster , font_red},
    {c_mystery, font_cyan}
};

unordered_map<int, string> Hero_ending_color_mapping = {
    {1, font_green},
    {2, font_red},
    {3, font_cyan},
    {4, font_blue},
    {5, font_red},
    {6, font_purple}, // hint voice, not ending
};
